### ISSUE TITLE
timestamp in publish/snapshot not being applied correctly

### ISSUE THREAD

**Issue by tongpu** [adfinis-sygroup/pyaptly#10]
In my configuration I have two publish endpoints, one with a snapshot and `timestamp: current` and another one with `timestamp: previous`, but after an update they both publish the same snapshot.

```yaml
mirror:
  trusty-main:
    archive: "http://ch.archive.ubuntu.com/ubuntu/"
snapshot:
  trusty-main-%T:
    mirror: "trusty-main"
    timestamp: {"time": "00:00"}
publish:
  ubuntu/latest:
    - distribution: "trusty"
      snapshots:
        - {"name": "trusty-main-%T", "timestamp": "current"}
  ubuntu/stable:
    - distribution: "trusty"
      snapshots:
        - {"name": "trusty-main-%T", "timestamp": "previous"}
```

Expected result:
```
  * trusty/latest [amd64] publishes {main: [trusty-main-20160613T0000Z]: Snapshot from mirror [trusty-main]: http://ch.archive.ubuntu.com/ubuntu/ trusty}
  * trusty/stable [amd64] publishes {main: [trusty-main-20160612T0000Z]: Snapshot from mirror [trusty-main]: http://ch.archive.ubuntu.com/ubuntu/ trusty}
```

Actual result:
```
  * trusty/latest [amd64] publishes {main: [trusty-main-20160613T0000Z]: Snapshot from mirror [trusty-main]: http://ch.archive.ubuntu.com/ubuntu/ trusty}
  * trusty/stable [amd64] publishes {main: [trusty-main-20160613T0000Z]: Snapshot from mirror [trusty-main]: http://ch.archive.ubuntu.com/ubuntu/ trusty}
```
